### PR TITLE
feat: Add Gob interface to Prefix

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by majst01** [comment]
Hi @Sh4d1 
thanks for your contribution, can you please elaborate on the use-case of gob encoded prefixes ?
Adding a test would make this PR more complete.

**Comment by Sh4d1** [comment]
Hey ! Initially it was in order to implement a new storage provider, but then I saw #15 so not sure it worth getting merged if that's the case. If ok though I'll add some tests indeed 😄

**Comment by majst01** [comment]
If you want to come around what is in #15 described, i'm happy to review as well. If your current code is covered by a test willing to merge.

**Comment by Sh4d1** [comment]
@majst01 just added a test :)

**Review by majst01 — APPROVED** [review]

**Comment by Sh4d1** [comment]
And FYI I use it to implement a Storage in k8s configmaps : https://github.com/Sh4d1/scaleway-k8s-vpc/blob/main/pkg/ipam/ipam.go :)

**Review by droid42 — APPROVED** [review]
LGTM

**Pull request merged**
