### PR TITLE
Add consul storage

### PR DESCRIPTION
**Pull request by tobias-urdin**
Implements the storage interface for Consul key-value storage. Basicly a copy of the Redis storage interface and changed to support the consul go API.

### CODE REVIEW

**Comment by tobias-urdin** [comment]
I implemented a key prefix so that we could run multiple go-ipam against same key-value. Seeing https://github.com/metal-stack/go-ipam/pull/43 now I assume that should be removed in favor of an official support like that.

**Comment by majst01** [comment]
Hi @tobias-urdin 

Thanks for the contribution ! Some thoughts from my side:

- I would also suggest to wait for #43, i am still not very happy with the current solution howto calculate the namespace key for the different storage backends, but this will be sorted out soon
- you must add the appropriate integration test infrastructure in testing_test.go, then all tests and benchmarks are executed against a real storage instance.
- i have seen no optimistic lock protection in the UpdatePrefix func, i dont know what ACID guarantees consul gives, but i am quite sure this is required there as well. Look in redis,go for reference.
- Last but not least some words in README.md should be added as well to the newly supported backend

**Comment by tobias-urdin** [comment]
Thanks for your feedback I will improve it based on that after the namespace support is done.

Best regards

**Comment by tobias-urdin** [comment]
Ops, wrong button :)

**Comment by tobias-urdin** [comment]
Will follow this up in another PR.

**Pull request closed without merging**
